name: Lint, Test and Coverage
on: push


jobs:
  Linting:
    name: Golang CI - Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/geektrust
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
          skip-go-installation: true
          only-new-issues: true
          args: --skip-dirs=pkg --timeout=3m
          working-directory: src/geektrust

  Unit_Test_Cases:
    
    name: Unit Test Cases
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/geektrust
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unit Test Cases
        env:
          ENV: "dev"
        run: go test ./... -parallel 4

  Test_Coverage:

    name: Test Coverage
    runs-on: ubuntu-latest
    needs: [ Linting, Unit_Test_Cases ]
    defaults:
      run:
        working-directory: src/geektrust
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Code Coverage
        env:
          ENV: "dev"
        run: |
          go test -parallel 4 -coverpkg=./... -coverprofile=profile.cov ./...
          go tool cover -func profile.cov
